<a href="https://colab.research.google.com/github/liberty0081/DeepLearningColab/blob/main/NeuralNetBackpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/NeuralNetwork')

import numpy as np
from keras.datasets import mnist
import keras
from NeuralNetworkOptimizer import *
from NeuralNetworkLayer import *

class NeuralNetwork():
    def __init__(self):
        #ネットワークの情報のリスト
        self.data                     = []
        #ネットワークの実体のリスト
        self.layer                    = []
        #実装済みの活性化関数のリスト
        self.activation_function_list = ["Swish", "ReLU", "Sigmoid"]
        #実装済みの出力層のリスト
        self.output_layer_list        = ["Softmax2CrossEntropy"]
        #実装済みの最適化手法のリスト
        self.optimizer_list           = ["SDG", "Adam", "Momentum", "AdaGrad"]

    #ニューラルネットに活性化関数を加えるメソッド
    def add_activation_function(self, func, size, indx = None):
        pass

    #ニューラルネットに全結合層(Affine層)を加えるメソッド
    def add_affine(self, input, output, optimizer, lr = 0.01, arg1 = None, arg2 = None, init = None, indx = None):
        pass

    #ニューラルネットにBatch Norm層を加えるメソッド
    def add_batch_norm(self, size, optimizer, lr = 0.01, arg1 = None, arg2 = None, indx = None):
        pass

    #ニューラルネットにOutput層を加えるメソッド
    def add_output_layer(self, func, size, indx = None)



"""
class NeuralNetwork():
    def __init__(self):
        self.data                = {}
        self.layer               = []
        self.flags               = {"IN":False, "OUT":False, "LAYERNUM":False, "NEURONNUM":False, "ACTFUNC":False, "OUTLAYER":False, "OPTIMIZER":False}
        self.actFuncList         = ["Swish", "ReLU", "Sigmoid"]
        self.outLayerList        = ["Softmax2CrossEntropy"]
        self.optimizerList       = ["SDG", "Adam", "Momentum", "AdaGrad"]
        self.createFlag          = False
        self.data["xavier"]      = False
        self.data["he"]          = False
        self.data["beforeBatch"] = False
        self.data["afterBatch"]  = False
        self.data["xavier"]      = False
        self.data["he"]          = False

    def __repr__(self):
        #ここにprint関数で表示させたい情報(ニューラルネットワークの実態の情報)を表示させるようにする。
        return "ここにprint関数で表示させたい情報(ニューラルネットワークの実態の情報)を表示させるようにする。"

    def inputSize(self, num):
        self.createFlag = False

        if type(num) == int and num > 0:
            self.data["input"] = num
            self.flags["IN"]   = True

        else:
            raise Exception("arg has to be <class 'int'> and 1 or more.")

    def outputSize(self, num):
        self.createFlag = False

        if type(num) == int and num > 0:
            self.data["output"] = num
            self.flags["OUT"]   = True

        else:
            raise Exception("arg has to be <class 'int'> and 1 or more.")

    def layerNumber(self, num):
        self.createFlag = False

        if type(num) == int and num > 1:
            self.data["layNum"]    = num
            self.flags["LAYERNUm"] = True

        else:
            raise Exception("arg has to be <class 'int'> and 2 or more.")

    def neuronNumber(self, x) :
        self.createFlag = False

        if self.data["layNum"] is None:
            raise Exception("you have to run layerNumber method before.")

        elif type(x) == int or type(x) == list:
            if type(x) == int:
                if x > 1:
                    self.data["neuNum"]     = [x]*(self.data["layNum"] - 1)
                    self.flags["NEURONNUM"] = True
                    
                else:
                    raise Exception("arg has to be 2 or more.")

            elif type(x) == list:
                if len(x) == len([i for i in x if type(i) == int and i > 1]):
                    if len(x) + 1 == self.data["layNum"]:
                        self.data["neuNum"]     = x
                        self.flags["NEURONNUM"] = True
                    
                    else:
                        raise Exception("length of list has to be 'arg of layerNumber - 1'.")

                else:
                    raise Exception("elms of list have to be <class 'int'> and 2 or more")

        else:
            raise Exception("arg has to be <class 'int'> or <class 'list'>")

    def actFunction(self, name):
        self.createFlag = False

        if name in self.actFuncList:
            self.data["actFunc"]  = name
            self.flags["ACTFUNC"] = True
        
        else:
            raise Exception("arg has to be an appropriate function name. appropriate function names are in NeuralNetwork.actFuncList.")

    def outputLayer(self, name):
        self.createFlag = False

        if name in self.outLayerList:
            self.data["outLayer"]  = name
            self.flags["OUTLAYER"] = True

        else:
            raise Exception("arg has to be a layer name. appropriate layer names are in NeuralNetwork.outLayerList.")

    def batchNorm(self, afterAF = False):
        self.createFlag = False

        if not afterAF:
            if self.data["beforeBatch"]:
                self.data["beforeBatch"] = False

            elif self.data["afterBatch"]:
                self.data["afterBatch"] = False
                self.data["beforeBatch"] = True

            else:
                self.data["beforeBatch"] = True

        elif afterAF:
            if self.data["afterBatch"]:
                self.data["afterBatch"] = False

            elif self.data["beforeBatch"]:
                self.data["beforeBatch"] = False
                self.data["afterBatch"] = True

            else:
                self.data["afterBatch"] = True

        else:
            raise Exception("arg has to be <class 'bool'>.")

    def xavier(self):
        self.createFlag = False
        self.data["he"] = False

        if self.data["xavier"]:
            self.data["xavier"] = False

        else:
            self.data["xavier"] = True

    def he(self):
        self.createFlag     = False
        self.data["xavier"] = False

        if self.data["he"]:
            self.data["he"] = False

        else:
            self.data["he"] = True

    def optimizer(self, name, lr = None, arg1 = None, arg2 = None):
        self.createFlag = False

        if name in self.optimizerList:
            if (type(lr) == float or lr is None) and (type(arg1) == float or arg1 is None) and (type(arg2) == float or arg2 is None):
                self.data["optimizer"]["name"] = name
                self.data["optimizer"]["lr"]   = lr
                self.data["optimizer"]["arg1"] = arg1
                self.data["optimizer"]["arg2"] = arg2
                self.flags["OPTIMIZER"]        = True

            else:
                raise Exception("args have to be <class 'float'> or <class 'NoneType'>")
        
        else:
            raise Exception("name has to be a optimizer name. appropriate optimizer names are in NeuralNetwork.optimizerList.")

    def create(self):
        if not False in self.flags.values():
            num_list = self.data["neuNum"]
            num_list.insert(0, self.data["input"])
            num_list.append(self.datta["output"])

            for i in range(self.data["layNum"] - 1):
                dict = {}
                dict["Affine"] = Affine(num_list[i], num_list[i + 1])

                if self.data["actFunc"] == "Swish":
                    dict["ActivationFunction"] = Swish()
                
                if self.data["actFunc"] == "ReLU":
                    dict["ActivationFunction"] = ReLU()

                if self.data["actFunc"] == "Sigmoid":
                    dict["ActivationFunction"] = Sigmoid()

                if self.data["beforeBatch"]:
                    dict["BeforeBatchNorm"] = BatchNorm()

                if self.data["afterBatch"]:
                    dict["AfterBatchNorm"] = BatchNorm()

                if self.data["optimizer"]["name"] == "SDG":
                    if self.data["optimizer"]["lr"] is None:
                        dict["Optimizer"] = SDG()

                    else:
                        dict["Optimizer"] = SDG(lr = self.data["optimizer"]["lr"])

                if self.data["optimizer"]["name"] == "Momentum":
                    if self.data["optimizer"]["lr"] is None:
                        dict["Optimizer"] = Momentum(rv = self.data["optimizer"]["arg1"])

                    else:
                        dict["Optimizer"] = Momentum(lr = self.data["optimizer"]["lr"], rv = self.data["optimizer"]["arg1"])

                if self.data["optimizer"]["name"] == "AdaGrad":
                    if self.data["optimizer"]["lr"] is None:
                        dict["Optimizer"] = AdaGrad()

                    else:
                        dict["Optimizer"] = AdaGrad(lr = self.data["optimizer"]["lr"])

                if self.data["optimizer"]["name"] == "Adam":
                    if self.data["optimizer"]["lr"] is None :
                        dict["Optimizer"] = Adam(beta1 = self.data["optimizer"]["arg1"], beta2 = self.data["optimizer"]["arg2"])

                    else:
                        dict["Optimizer"] = Adam(lr = self.data["optimizer"]["lr"], beta1 = self.data["optimizer"]["arg1"], beta2 = self.data["optimizer"]["arg2"])

                self.layer.append(dict)

            dict = {}
            dict["Affine"] = Affine(num_list[self.data["layNum"] - 1], num_list[self.data["layNum"]])

            if self.data["outLayer"] == "Softmax2CrossEntropy":
                dict["OutputFunction"] = Softmax2CrossEntropy()

            if self.data["optimizer"]["name"] == "SDG":
                if self.data["optimizer"]["lr"] is None:
                    dict["Optimizer"] = SDG()

                else:
                    dict["Optimizer"] = SDG(lr = self.data["optimizer"]["lr"])

            if self.data["optimizer"]["name"] == "Momentum":
                if self.data["optimizer"]["lr"] is None:
                    dict["Optimizer"] = Momentum(rv = self.data["optimizer"]["arg1"])

                else:
                    dict["Optimizer"] = Momentum(lr = self.data["optimizer"]["lr"], rv = self.data["optimizer"]["arg1"])

            if self.data["optimizer"]["name"] == "AdaGrad":
                if self.data["optimizer"]["lr"] is None:
                    dict["Optimizer"] = AdaGrad()

                else:
                    dict["Optimizer"] = AdaGrad(lr = self.data["optimizer"]["lr"])

            if self.data["optimizer"]["name"] == "Adam":
                if self.data["optimizer"]["lr"] is None :
                    dict["Optimizer"] = Adam(beta1 = self.data["optimizer"]["arg1"], beta2 = self.data["optimizer"]["arg2"])

                else:
                    dict["Optimizer"] = Adam(lr = self.data["optimizer"]["lr"], beta1 = self.data["optimizer"]["arg1"], beta2 = self.data["optimizer"]["arg2"])

            self.layer.append(dict)

            if self.data["xavier"]:
                for j in range(self.data["layNum"]):
                    self.layer[j]["Affine"].W = np.random.randn(self.layer[j]["Affine"].data["IN"], self.layer[j]["Affine"].data["OUT"])/np.aqrt(self.layer[j]["Affine"].data["IN"])

            if self.data["he"]:
                for j in range(self.data["layNum"]):
                    self.layer[j]["Affine"].W = np.random.randn(self.layer[j]["Affine"].data["IN"], self.layer[j]["Affine"].data["OUT"])*np.aqrt(2/self.layer[j]["Affine"].data["IN"])

            self.createFlag = True

        else:
            raise Exception("you have to run appropriate method.")
                    
class NeuralNetwork():
    def __init__(self, inputSize, outputSize, layerNumber, neuronNumber, inputLayer = "Sigmoid", outputLayer = "Softmax2CrossEntropy", \
                 optimizer = "SDG", learningRate = 0.01, momentumRV = None, adamBeta1 = None, adamBeta2 = None):
        self.data        = {"IN":inputSize, "OUT":outputSize, "LayerNumber":layerNumber, "NeuronNumber":neuronNumber, \
                            "LearningRate":learningRate, "MomentumRV":momentumRV, "AdamBeta1":adamBeta1, "AdamBeta2":adamBeta2}
        self.layer       = []
        self.optimizer   = []

        if inputLayer == "Swish":
            self.layer.append((Affine(self.data["IN"], self.data["NeuronNumber"]), Swish()))
            for i in range(1, self.data["LayerNumber"] - 1):
                self.layer.append((Affine(self.data["NeuronNumber"], self.data["NeuronNumber"]), Swish()))

        if inputLayer == "Sigmoid":
            self.layer.append((Affine(inputSize=self.data["IN"], outputSize=self.data["NeuronNumber"]), Sigmoid()))
            for i in range(1, self.data["LayerNumber"] - 1):
                self.layer.append((Affine(self.data["NeuronNumber"], self.data["NeuronNumber"]), Sigmoid()))

        if inputLayer == "ReLU":
            self.layer.append((Affine(self.data["IN"], self.data["NeuronNumber"]), ReLU()))
            for i in range(1, self.data["LayerNumber"] - 1):
                self.layer.append(((Affine(self.data["NeuronNumber"], self.data["NeuronNumber"]), ReLU())))

        if outputLayer == "Softmax2CrossEntropy":
            self.layer.append((Affine(self.data["NeuronNumber"], self.data["OUT"]), Softmax2CrossEntropy()))

        self.layer = tuple(self.layer)

        if optimizer == "SDG":
            for i in range(self.data["LayerNumber"]):
                self.optimizer.append(SDG(self.data["LearningRate"]))

        if optimizer == "Momentum":
            for i in range(self.data["LayerNumber"]):
                self.optimizer.append(Momentum(self.data["LearningRate"], self.data["MomentumRV"]))

        if optimizer == "AdaGrad":
            for i in range(self.data["LayerNumber"]):
                self.optimizer.append(AdaGrad(self.data["LearningRate"]))

        if optimizer == "Adam":
            for i in range(self.data["LayerNumber"]):
                self.optimizer.append(Adam(self.data["LearningRate"], self.data["AdamBeta1"], self.data["AdamBeta2"]))


        self.optimizer = tuple(self.optimizer)

    def xavier(self):
        for i in range(self.data["LayerNumber"]):
            self.layer[i][0].W = np.random.randn(self.layer[i][0].data["IN"], self.layer[i][0].data["OUT"])/np.sqrt(self.layer[i][0].data["IN"])

    def he(self):
        for i in range(self.data["LayerNumber"]):
            self.layer[i][0].W = np.random.randn(self.layer[i][0].data["IN"], self.layer[i][0].data["OUT"])*np.sqrt(2/self.layer[i][0].data["IN"])

    def forward(self, x, t):
        z = x
        for i in range(self.data["LayerNumber"] - 1):
            z = self.layer[i][1].forward((self.layer[i][0].forward(z)))

        loss = self.layer[self.data["LayerNumber"] - 1][1].forward(self.layer[self.data["LayerNumber"] - 1][0].forward(z), t)

        return loss

    def backward(self):
        delta = self.layer[self.data["LayerNumber"] - 1][0].backward(self.layer[self.data["LayerNumber"] - 1][1].backward())
        for i in range(self.data["LayerNumber"] - 2, -1, -1):
            delta = self.layer[i][0].backward(self.layer[i][1].backward(delta))

    def optimize(self):
        for i in range(self.data["LayerNumber"]):
            self.optimizer[i].learning(self.layer[i][0].W, self.layer[i][0].dW, self.layer[i][0].b, self.layer[i][0].db)

    def accuracy(self, x, t):
        z = x
        for i in range(self.data["LayerNumber"] - 1):
            z = self.layer[i][1].test_forward((self.layer[i][0].test_forward(z)))

        y = self.layer[self.data["LayerNumber"] - 1][1].test_forward(self.layer[self.data["LayerNumber"] - 1][0].test_forward(z))

        a = np.argmax(y, axis=1)
        b = np.argmax(t, axis=1)
        accuracy = float(np.sum(a == b))/float(x.shape[0])

        return accuracy


(x_train, t_train), (x_test, t_test) = mnist.load_data()

x_train  = x_train.reshape(60000, 784)
x_test   = x_test.reshape(10000, 784)
x_train  = x_train.astype('float32')
x_test   = x_test.astype('float32')
x_train /= 255
x_test  /= 255
t_train  = keras.utils.np_utils.to_categorical(t_train, 10)
t_test   = keras.utils.np_utils.to_categorical(t_test, 10)

batch_size = 100
net1 = NeuralNetwork(inputSize=x_train.shape[1], outputSize=t_train.shape[1], layerNumber = 5, neuronNumber = 100, inputLayer = "Swish", optimizer = "Adam", learningRate = 0.001)
net1.he()

for epoch in range(10):
    if epoch < 10:
        print("{}エポック:認識精度{:.2f}%".format("00" + str(epoch), net1.accuracy(x_test, t_test)*100))
    
    elif epoch < 100:
        print("{}エポック:認識精度{:.2f}%".format("0" + str(epoch), net1.accuracy(x_test, t_test)*100))

    for i in range(int(x_train.shape[0]/batch_size)):
        batch_mask = np.random.choice(x_train.shape[0], batch_size)
        x_batch = x_train[batch_mask]
        t_batch = t_train[batch_mask]

        net1.forward(x_batch, t_batch)
        net1.backward()
        net1.optimize()

print("{}エポック:認識精度{:.2f}%".format("0" + str(epoch + 1), net1.accuracy(x_test, t_test)*100))
print("---------------------------------")
"""

net = NeuralNetwork()
print(net)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ここにprint関数で表示させたい情報(ニューラルネットワークの実態の情報)を表示させるようにする。


In [ ]:

import numpy as np

x = np.array([[-1,1,1,1,1],
              [1,-1,1,1,1],
              [1,1,-1,1,1],
              [1,1,1,-1,1],
              [1,1,1,1,-1],])
w = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [3,2,1],
              [1,1,1]])
print(1/np.sqrt(w*w))
w

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]
 [0.33333333 0.5        1.        ]
 [1.         1.         1.        ]]


array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [3, 2, 1],
       [1, 1, 1]])

In [ ]:
import numpy as np

class C:
    def __init__(self):
        self.x = np.random.randn(5)

class K:
    def __init__(self):
        self.v = None
    
    def eee(self, x, lr = 0.01, momentum = 10):
        if self.v is None:
            self.v = np.zeros_like(x)
        
        self.v = momentum*self.v - lr*x
        x += self.v 

class G:
    def __init__(self):
        self.layer = C()
        self.op = K()

    def momentum(self):
        self.op.eee(self.layer.x)

a = G()
print(a.layer.x)
a.momentum()
print(a.layer.x)

[-0.68319804 -0.04941163 -0.54388934 -3.44836962 -0.25866701]
[-0.67636606 -0.04891752 -0.53845045 -3.41388592 -0.25608034]


In [ ]:
print(type(1))

<class 'int'>


In [ ]:
import numpy as np
a = list(np.random.randint(-5, 5, (10)))
print(a)
print((False in list(np.array(a) > 0)))
print(True in list(np.array(a) == int))
a

[0, -1, -5, 4, 2, -2, 2, -4, 1, 2]
True
False


[0, -1, -5, 4, 2, -2, 2, -4, 1, 2]

In [ ]:
[1]*5

[1, 1, 1, 1, 1]