<a href="https://colab.research.google.com/github/liberty0081/DeepLearningColab/blob/develop/NeuralNetBackpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/NeuralNetwork')

import numpy as np
from keras.datasets import mnist
import keras
from NeuralNetworkOptimizer import *
from NeuralNetworkLayer import *

class NeuralNetwork():
    def __init__(self):
        #ネットワークの情報のリスト
        self.data                     = []
        #ネットワークの実体のリスト
        self.layer                    = []
        #実装済みの活性化関数のリスト
        self.activation_function_list = ["Swish", "ReLU", "Sigmoid"]
        #実装済みの出力層のリスト
        self.output_layer_list        = ["Softmax2CrossEntropy"]
        #実装済みの最適化手法のリスト
        self.optimizer_list           = ["SDG", "Adam", "Momentum", "AdaGrad"]
        #ネットワークの層数を保持するインスタンス
        self.length                   = None


    #構成したニューラルネットの情報をprint関数で表示
    def __repr__(self):
        pass

    #ニューラルネットに活性化関数を加えるメソッド
    def add_activation_function(self, func, size):
        #前のレイヤーが存在するか判定しする。
        #存在したら、前のレイヤーが出力層かどうか判定(前のレイヤーの[OUTFLAG]を見る)。true→エラー、false→sizeが前のレイヤーのsizeかoutputと値が一致するか判定する。false→エラー、true→次
        #存在していなかったら→次
        #funcが活性化関数のリストにあるか判定。false→エラー、true→次
        #{"LAYER":func, "SIZE":size, "OUTFLAG":False}のディクショナリを作ってself.dataにappend
        pass

    #ニューラルネットに全結合層(Affine層)を加えるメソッド
    def add_affine(self, input, output, optimizer, lr = 0.01, arg1 = None, arg2 = None, init = None):
        #前のレイヤーが存在するか判定しする。
        #存在したら、前のレイヤーが出力層かどうか判定(前のレイヤーの[OUTFLAG]を見る)。true→エラー、false→inputが前のレイヤーのsizeかoutputと値が一致するか判定する。false→エラー、true→次
        #存在していなかったら→次
        #optimizerが最適化手法のリストにあるか判定。false→エラー、true→次
        #{"LAYER":"Affine", "SIZE":(input, output), "OPTIMIZER":optimizer, "LR":lr, ARG1":arg1, "ARG2":arg2, "OUTFLAG":False}のディクショナリを作ってself.dataにappend
        pass

    #ニューラルネットにBatch Norm層を加えるメソッド
    def add_batch_norm(self, size, optimizer, lr = 0.01, arg1 = None, arg2 = None):
        #前のレイヤーが存在するか判定しする。
        #存在したら、前のレイヤーが出力層かどうか判定(前のレイヤーの[OUTFLAG]を見る)。true→エラー、false→sizeが前のレイヤーのsizeかoutputと値が一致するか判定する。false→エラー、true→次
        #存在していなかったら→次
        #optimizerが最適化手法のリストにあるか判定。false→エラー、true→次
        #{"LAYER":"BatchNorm", "SIZE":size, "OPTIMIZER":optimizer, "LR":lr, "ARG1":arg1, "ARG2":arg2, "OUTFLAG":False}のディクショナリを作ってself.dataにappend
        pass

    #ニューラルネットにOutput層を加えるメソッド
    def add_output_layer(self, func, size):
        #前のレイヤーが存在するか判定しする。
        #存在したら、前のレイヤーが出力層かどうか判定(前のレイヤーの[OUTFLAG]を見る)。true→エラー、false→sizeが前のレイヤーのsizeかoutputと値が一致するか判定する。false→エラー、true→次
        #存在していなかったら→次
        #funcが出力層のリストにあるか判定。false→エラー、true→次
        #{"LAYER":func, "SIZE2:size, "OUTFLAG":True}のディクショナリを作ってself.dataにappend
        #self.lengthに層の数を保持させる。
        pass

    #設定した情報からニューラルネットの実体を作るメソッド
    def create(self):
        #層の数だけ繰り返す。
        #dict = {} 作る
        #data[i]["LAYER"]が"Swish"ならdict["LAYER"] = Swish()
        #data[i]["LAYER"]が"ReLU"ならdict["LAYER"] = ReLU()
        #data[i]["LAYER"]が"Sigmoid"ならdict["LAYER"] = Sigmoid()
        #data[i]["LAYER"]が"Softmax2CrossEntropy"ならdict["LAYER"] = Softmax2CrossEntropy()
        #data[i]["LAYER"]が"Affine"ならdict["LAYER"] = Affine(data[i]["SIZE"][0], data[i]["SIZE"][1])
        #data[i]["LAYER"]が"BatchNorm"ならdict["LAYER"] = BatchNorm()
        #data[i]["OPTIMIZER"]が"SDG"ならdict["OPTIMIZER"] = SDG(lr = data[i]["LR"])
        #data[i]["OPTIMIZER"]が"Momentum"ならdict["OPTIMIZER"] = Momentum(lr = data[i]["LR"], rv = data[i]["ARG1"])
        #data[i]["OPTIMIZER"]が"AdaGrad"ならdict["OPTIMIZER"] = AdaGrad(lr = data[i]["LR"])
        #data[i]["OPTIMIZER"]が"Adam"ならdict["OPTIMIZER"] = Adam(lr = data[i]["LR"], beta1 = data[i]["ARG1"], beta2 = data[i]["ARG2"])
        #data[i]["OPTIMIZER"]がNoneならdict["OPTIMIZER"] = None
        #dictをself.layerにappend
        pass

    #各レイヤーのforwardメソッドを回すメソッド
    def forward(self, x, t):
        pass

    #各レイヤーのbackwardメソッドを回すメソッド
    def backward(self):
        pass

    #テストデータで認識精度を出すメソッド
    def accuracy(self, x, t):
        pass

    #ニューラルネットの情報と学習したパラメータを.py外部ファイルに書き出すメソッド
    def save(self):
        pass

    #saveメソッドで書き出された.pyファイルを読み込むメソッド
    def load(self, file):
        pass

    

net = NeuralNetwork()
print(net)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ここにprint関数で表示させたい情報(ニューラルネットワークの実態の情報)を表示させるようにする。


In [ ]:

import numpy as np

x = np.array([[-1,1,1,1,1],
              [1,-1,1,1,1],
              [1,1,-1,1,1],
              [1,1,1,-1,1],
              [1,1,1,1,-1],])
w = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [3,2,1],
              [1,1,1]])
print(1/np.sqrt(w*w))
w

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]
 [0.33333333 0.5        1.        ]
 [1.         1.         1.        ]]


array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [3, 2, 1],
       [1, 1, 1]])

In [ ]:
import numpy as np

class C:
    def __init__(self):
        self.x = np.random.randn(5)

class K:
    def __init__(self):
        self.v = None
    
    def eee(self, x, lr = 0.01, momentum = 10):
        if self.v is None:
            self.v = np.zeros_like(x)
        
        self.v = momentum*self.v - lr*x
        x += self.v 

class G:
    def __init__(self):
        self.layer = C()
        self.op = K()

    def momentum(self):
        self.op.eee(self.layer.x)

a = G()
print(a.layer.x)
a.momentum()
print(a.layer.x)

[-0.68319804 -0.04941163 -0.54388934 -3.44836962 -0.25866701]
[-0.67636606 -0.04891752 -0.53845045 -3.41388592 -0.25608034]


In [ ]:
print(type(1))

<class 'int'>


In [ ]:
import numpy as np
a = list(np.random.randint(-5, 5, (10)))
print(a)
print((False in list(np.array(a) > 0)))
print(True in list(np.array(a) == int))
a

[0, -1, -5, 4, 2, -2, 2, -4, 1, 2]
True
False


[0, -1, -5, 4, 2, -2, 2, -4, 1, 2]

In [ ]:
[1]*5

[1, 1, 1, 1, 1]