<a href="https://colab.research.google.com/github/liberty0081/DeepLearningColab/blob/develop/NeuralNetBackpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/NeuralNetwork')

import numpy as np
from keras.datasets import mnist
import keras
from NeuralNetworkOptimizer import *
from NeuralNetworkLayer import *

class NeuralNetwork():
    def __init__(self):
        #ネットワークの情報のリスト
        self.data                     = []
        #ネットワークの実体のリスト
        self.layer                    = []
        #実装済みの活性化関数のリスト
        self.activation_function_list = ["Swish", "ReLU", "Sigmoid"]
        #実装済みの出力層のリスト
        self.output_layer_list        = ["Softmax2CrossEntropy"]
        #実装済みの最適化手法のリスト
        self.optimizer_list           = ["SDG", "Adam", "Momentum", "AdaGrad"]

    #ニューラルネットに活性化関数を加えるメソッド
    def add_activation_function(self, func, size, indx = None):
        pass

    #ニューラルネットに全結合層(Affine層)を加えるメソッド
    def add_affine(self, input, output, optimizer, lr = 0.01, arg1 = None, arg2 = None, init = None, indx = None):
        pass

    #ニューラルネットにBatch Norm層を加えるメソッド
    def add_batch_norm(self, size, optimizer, lr = 0.01, arg1 = None, arg2 = None, indx = None):
        pass

    #ニューラルネットにOutput層を加えるメソッド
    def add_output_layer(self, func, size, indx = None)

net = NeuralNetwork()
print(net)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ここにprint関数で表示させたい情報(ニューラルネットワークの実態の情報)を表示させるようにする。


In [ ]:

import numpy as np

x = np.array([[-1,1,1,1,1],
              [1,-1,1,1,1],
              [1,1,-1,1,1],
              [1,1,1,-1,1],
              [1,1,1,1,-1],])
w = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [3,2,1],
              [1,1,1]])
print(1/np.sqrt(w*w))
w

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]
 [0.33333333 0.5        1.        ]
 [1.         1.         1.        ]]


array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [3, 2, 1],
       [1, 1, 1]])

In [ ]:
import numpy as np

class C:
    def __init__(self):
        self.x = np.random.randn(5)

class K:
    def __init__(self):
        self.v = None
    
    def eee(self, x, lr = 0.01, momentum = 10):
        if self.v is None:
            self.v = np.zeros_like(x)
        
        self.v = momentum*self.v - lr*x
        x += self.v 

class G:
    def __init__(self):
        self.layer = C()
        self.op = K()

    def momentum(self):
        self.op.eee(self.layer.x)

a = G()
print(a.layer.x)
a.momentum()
print(a.layer.x)

[-0.68319804 -0.04941163 -0.54388934 -3.44836962 -0.25866701]
[-0.67636606 -0.04891752 -0.53845045 -3.41388592 -0.25608034]


In [ ]:
print(type(1))

<class 'int'>


In [ ]:
import numpy as np
a = list(np.random.randint(-5, 5, (10)))
print(a)
print((False in list(np.array(a) > 0)))
print(True in list(np.array(a) == int))
a

[0, -1, -5, 4, 2, -2, 2, -4, 1, 2]
True
False


[0, -1, -5, 4, 2, -2, 2, -4, 1, 2]

In [ ]:
[1]*5

[1, 1, 1, 1, 1]